### ISSUE TITLE
Add the prompts under an already existing heading?

### ISSUE THREAD

**Issue by Airiswindy** [Erl-koenig/obsidian-dailyPrompt#1]
I have my daily notes structured in a very personal way and I would like to know if its possible to have the prompts under an already existing heading as I don't want to scroll all the way down to see my responses

**Comment by Erl-koenig** [comment]
@Airiswindy Have you tried using the setting "Prompt section heading" to use your own custom heading?

**Comment by Airiswindy** [comment]
yeah that worked but unfortunately it removed other text i had under the heading might just make another heading for prompts thanks for the help
